services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cinema'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'
  app:
    image: 'cinema-app'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgres'
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/cinema'
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'password'