spring:
  application:
    name: cinema

  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: "1000ms"
      quiet-period: "100ms"
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5434/cinema
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
        testcontainers: INFO

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

data:
  source:
    - test.xlsx
    - src/main/resources/
